name: coverage_PR

# Controls when the workflow will run
on: pull_request

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout badges branch dedicated to storing badges only
        uses: actions/checkout@v3
        with:
          ref: badges
          path: badges

      - name: Generate report
        run: cd sessionkotlin && gradle wrapper && ./gradlew clean check build jacocoTestReport

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branches = ${{ steps.jacoco.outputs.branches }}"

      - name: Upload Jacoco coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: sessionkotlin/build/reports/jacoco/codeCoverageReport
