name: pull_request_flow

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tests
        run: cd sessionkotlin && gradle wrapper && ./gradlew clean build
        env:
          USERNAME: ${{ secrets.ACTIONS_ACTOR }}
          TOKEN: ${{ secrets.ACTIONS_TOKEN }}

      - name: Checkout badges branch dedicated to storing badges only
        uses: actions/checkout@v3
        with:
          ref: badges
          path: badges

      - name: Generate report
        run: cd sessionkotlin && gradle wrapper && ./gradlew clean build codeCoverageReport
        env:
          USERNAME: ${{ secrets.ACTIONS_ACTOR }}
          TOKEN: ${{ secrets.ACTIONS_TOKEN }}

      - name: Upload Jacoco coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: sessionkotlin/build/reports/jacoco/codeCoverageReport
