name: pull_request_flow

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add summary header
        run: echo "### Summary" >> $GITHUB_STEP_SUMMARY

      - name: Tests
        working-directory: sessionkotlin
        run: ./gradlew clean build codeCoverageReport
        env:
          USERNAME: ${{ secrets.ACTIONS_ACTOR }}
          TOKEN: ${{ secrets.ACTIONS_TOKEN }}

      - name: Log test summary
        if: always()
        run: |
          echo "#### Tests" >> $GITHUB_STEP_SUMMARY
          echo "| Module | Status | Passed | Failed | Skipped | Duration |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|--------|--------|--------|---------|----------|" >> $GITHUB_STEP_SUMMARY
          cat sessionkotlin/build/test_summary.md >> $GITHUB_STEP_SUMMARY

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: sessionkotlin/build/reports/jacoco/codeCoverageReport/codeCoverageReport.csv

      - name: Log coverage percentage
        run: |
          echo "#### Jacoco report" >> $GITHUB_STEP_SUMMARY
          echo "- Coverage: ${{ steps.jacoco.outputs.coverage }}" >> $GITHUB_STEP_SUMMARY
          echo "- Branch coverage: ${{ steps.jacoco.outputs.branches }}" >> $GITHUB_STEP_SUMMARY

      - name: Upload Jacoco coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: sessionkotlin/build/reports/jacoco/codeCoverageReport
